# Generated by Django 3.2.7 on 2021-09-12 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0002_alter_image_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='users_like',
            field=models.ManyToManyField(related_name='image_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
